<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 3" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="C:\Users\ykm09\workspace\pythonTest\src\drawTcpClient.py" status="error" test="drawTcpClient" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\ykm09\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:\Users\ykm09\workspace\pythonTest\src\drawTcpClient.py", line 72, in <module>
    sys.exit(App.exec())
SystemExit: 0
ERROR: Module: drawTcpClient could not be imported (file: C:\Users\ykm09\workspace\pythonTest\src\drawTcpClient.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="pythonTest drawTcpClient.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
